### ISSUE TITLE
Move away from buildx

### ISSUE THREAD

**Issue by SgtCoDFish** [cert-manager/trust-manager#112]
The [release](https://kubernetes.slack.com/archives/CDEQJ0Q8M/p1675349661930549) of trust-manager 0.4.0 hit several issues relating to buildx. For go, it seems incredibly heavyweight since rather than cross compiling, say, the arm64 version of trust-manager with the amd64 version of go, it instead runs the native arm64 binary in qemu, inside a container.

There are a lot of things that can go wrong there, and during the build for 0.4.0 we saw a deadlock - the cause of which was very difficult to pin down.

We use `ko` in other projects and should consider using that here too.

**Comment by inteon** [comment]
This has been fixed, we now use Ko.
