### ISSUE TITLE
How to create docker-registry secret?

### ISSUE THREAD

**Issue by robodrome** [cert-manager/trust-manager#119]
I haven't found a way to get help, so perhaps the main issue for me is: is there a discord channel or something for questions? Sorry if this is not the correct way to do that.

I want to create a docker-registry secret for pulling images from local registry (trow). It works when I manually create a secret key, but I want to use trust-manager to handle that.

Method I use now:

```bash
kubectl create secret docker-registry trow-mydomain-credentials \
--namespace mynamespace \
--docker-server=trow.mydomain.home \
--docker-username='USERNAME' \
--docker-password='PASSWORD' \
--docker-email=info@mydomain.home
```

See https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/

**Comment by ebuildy** [comment]
trust-manager is not for that use-case!

**Comment by robodrome** [comment]
Ah ok. Thanks.
