### ISSUE TITLE
Allow node selection based on nodeSelector, tolerations, affinities and topologySpreadConstraints

### ISSUE THREAD

**Issue by mikhailadvani** [cert-manager/trust-manager#13]
Affinities and topologySpreadConstraints can wait for nodeSelector(enforced by validatingwebhooks) and tolerations(where all nodes run with taints) are more important to support in the helm chart

**Comment by b44rawat** [comment]
+1

**Comment by b44rawat** [comment]
I hope the development of this feature is in progress.
