### ISSUE TITLE
Unable to run Trust Manager without cert manager

### ISSUE THREAD

**Issue by ishantagarwal95** [cert-manager/trust-manager#132]
I want to install Trust Manager without cert manager. For that I removed the certificate.yaml file from helm chart. I also saved _ca.crt_, _tls.crt_, _tls.key_ files in trust-manager-tls secret. This corresponds to the certificate I got signed from AWS Private CA.
I then tried to install trust manager via helm chart. Trust Manager got installed successfully.
Now I applied a Bundle to sync the ca.crt file to example config maps. This gave me the following error:
```
Internal error occurred: failed calling webhook "trust.cert-manager.io": failed to call webhook: Post "https://trust-manager.cert-manager.svc:443/validate?timeout=5s": x509: certificate signed by unknown authority
```

Can someone please help me here. I just want to use a certificate issued by AWS Private CA and sync is CA certificate to other configmaps. For this, I don't want to use cert manager.

**Comment by erikgb** [comment]
I think trust-manager (at least) depends on cert-manager to provide a certificate for the validating webhook in trust-manager. Obtaining webhook certificates is always a painful process, and there are at least a dozen different approaches to this in the Kubernetes operator landscape. As trust-manger is maintained by the cert-manager team, I think it seem legit to use cert-manager there. Why do you not want to install cert-manager?

**Comment by SgtCoDFish** [comment]
Hey, thanks for raising this!  I'm gonna close since #157 implements this - keep an eye out for the next trust-manager release which should enable this 👍
