### ISSUE TITLE
Upgrade chart to apiVersion v2

### ISSUE THREAD

**Issue by mikhailadvani** [cert-manager/trust-manager#14]
Installing the chart with apiVersion v1 through kustomize along with a bundle resource in the same go is resulting in dry run errors because the CRDs are not evaluated separately

**Comment by SgtCoDFish** [comment]
Relevant docs: https://helm.sh/docs/topics/charts/#the-apiversion-field

I think this makes sense to do!

**Comment by joscabmar** [comment]
I am getting this message while installing the chart: 
```
Chart.yaml: chart type is not valid in apiVersion 'v1'. It is valid in apiVersion 'v2'
```

**Comment by SgtCoDFish** [comment]
Since #61 was merged I think this can be closed. Looks like it was just missed at the time. Thanks for raising!
