### ISSUE TITLE
Override namespace installation

### ISSUE THREAD

**Issue by morozovcookie** [cert-manager/trust-manager#145]
Hello everyone! I would like to propose to you to add a `namespaceOverride` parameter in `values.yaml` like it was done for cert-manager. 

In my case I have a single big chart, which used to install cert-manager, trust-manager and other stuff. In current configuration namespaced resources will be installed in release namespace, but I want to control that behavior.

**Comment by hawksight** [comment]
@SgtCoDFish this is another good first issue I think, a minor helm chart change.

@morozovcookie so you'd want something like this: https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/templates/deployment.yaml#L5

Where the logic in the helper is basically this: https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/templates/_helpers.tpl#L164C1-L174C12
