### ISSUE TITLE
No support for EKS in helm

### ISSUE THREAD

**Issue by ChevronTango** [cert-manager/trust-manager#159]
Cert-Manager and Trust-Manager both use ValidatingWebhookConfiguration as part of their helm deployments, however cert-manager has specifically got support for AWS EKS, where these webhooks require `hostnetwork: true` to be set. This is because the EKS control plane sits apart from the rest of the cluster. Cert-manager [documents](https://cert-manager.io/docs/installation/compatibility/#aws-eks) the config changes needed to work in EKS but currently the Trust-Manager helm chart neither supports these changes nor documents how it can done. Without these changes, it is currently not possible to have a stable deployment of trust-manager on AWS EKS.

if deploying right now, you would see errors like the following:

```
cannot patch "cert-bundle" with kind Bundle: Internal error occurred: failed calling webhook "trust.cert-manager.io": failed to call webhook: Post "https://trust-manager.default.svc:443/validate?timeout=5s": Address is not allowed
```

The helm chart's webhook should be changed to allow a hostNetwork flag to be added so that EKS can be supported, which should also bring the chart in line with the cert-manager helm chart..

**Comment by cablespaghetti** [comment]
@ChevronTango Just to be completely clear, this is only necessary if using a non-standard CNI with EKS. We've been using this on EKS for sometime without hostnetworking turned on using the standard VPC CNI.

**Comment by ChevronTango** [comment]
> @ChevronTango Just to be completely clear, this is only necessary if using a non-standard CNI with EKS. We've been using this on EKS for sometime without hostnetworking turned on using the standard VPC CNI.

Ahh yes. Quite right. Good distinction to make!

**Comment by erikgb** [comment]
I believe this issue is resolved by https://github.com/cert-manager/trust-manager/pull/156.

/close
