### ISSUE TITLE
New alpha version helm chart kubeVersion needs a dash 0 at the end to work in eks?

### ISSUE THREAD

**Issue by dsand1234** [cert-manager/trust-manager#181]
I noticed a recent change for the newest alpha version v0.7.0-alpha.0 has:

\- kubeVersion: ">= 1.22.0-0"
\+kubeVersion: ">= 1.25.0"

I get errors when trying to install the helm chart on EKS due to EKS having a platform version, as I believe it needs the "-0"?  It basically says that the kubernetes version does not meet the minimum requirements even though my k8s version is at 1.25.

**Comment by erikgb** [comment]
Interesting! Thanks for notifying @dsand1234! I am not an expert on Helm, and the docs are not clear in this area: https://helm.sh/docs/topics/charts/#the-kubeversion-field. I have installed the latest alpha release on Openshift without issues. But I guess there is a reason the value had a `-0` at the end before https://github.com/cert-manager/trust-manager/commit/a0b904de6c2136ea2a78b349cefa2b6ff386500b. Do you want to raise a PR to fix this?

**Comment by dsand1234** [comment]
Here is a ticket that describes the issue:  https://github.com/helm/helm/issues/10375
Helm assumes everything after the semVer "dash" to be a pre-release version rather than just metadata.

**Comment by erikgb** [comment]
Thanks! So it's AWS not following SemVer? I'm guessing that not gonna change. 😊
