### ISSUE TITLE
trust-manager and Kubernetes version compatibility

### ISSUE THREAD

**Issue by kichel98** [cert-manager/trust-manager#227]
Hello,
I want to use trust-manager but on previous K8s versions like 1.19 and 1.21. I ran through previous releases of trust-manager and your compatibility matrix looks like:
  | trust-manager version | kubeVersion |
  | --------------------- | ----------- |
  | latest (v0.7.0) | >= 1.25.0-0 |
  | v0.6.0 | >= 1.22.0-0 |
  | v0.5.0 | >= 1.22.0-0 |
  | v0.4.0 | >= 1.22.0-0 |
  | v0.3.0 | no kubeVersion in Chart.yaml |

My questions are:
1. Do you remember what was behind introducing requirement `kubeVersion >= 1.22.0-0` in v0.4.0?
2. Was this requirement also valid in previous releases, but simply not included in `Chart.yaml`? In other words, do you think we can try to use v0.3.0 for kubeVersion=1.19?

**Comment by erikgb** [comment]
@kichel98 The K8s requirements were introduced in https://github.com/cert-manager/trust-manager/commit/57f6cdfc5974865bddd3eb3536a38cdaaed6f225, and I am not sure why 1.22 was chosen as the minimum K8s requirement. Trying out trust-manager 0.3.0 on your legacy clusters is probably worth a try. But you should really consider upgrading to newer Kubernetes. These versions have been EOL for a long time now: https://endoflife.date/kubernetes

**Comment by kichel98** [comment]
Thank you, I'll try. Could you send me a link to docs for this version?

**Comment by erikgb** [comment]
I don't think we have docs for such old versions available anymore. I suggest you upgrade to a supported version of trust-manager.

/close
