### ISSUE TITLE
Using `trust-manager` for generating keystores

### ISSUE THREAD

**Issue by k8ieone** [cert-manager/trust-manager#283]
We have an application, which sources private keys stored in a `.jks` keystore.

I wanted to use `trust-manager` for generating these keystores from `.pem` private key files, but it seems this is not a supported use case as of now.

```
invalid PEM block in bundle: only CERTIFICATE blocks are permitted but found 'PRIVATE KEY'
```

I knew the chances of this just working were slim, since the documentation only talks about truststores and trust bundles.

Do you think this could be a supported use case in the future? Is there a different project that does this?

**Comment by erikgb** [comment]
@k8ieone I am not sure if I understand your use case. Are you looking for an operator to convert PEM to JKS in general? I am not aware of any - if that's what you are looking for.

**Comment by erikgb** [comment]
The goal of trust-manager is specifically the distribution of trust anchors, and not a generic format converter.

Some suggestions for you use case:

- migrate the application to support PEM format (JKS is somehow deprecated)
- add an init-container to the application pod to convert from PEM to JKS using the standard JDK `keytool` CLI.

I am going to close this issue as not relevant for trust-manager.

/close

**Comment by k8ieone** [comment]
Alright, thanks for the suggestion.

Just for the record, if anyone happens to find this issue - migrating the app is not a possibility at this time.

Using an init container with an emptydir volume sounds like a good approach, which we'll likely use.
