### ISSUE TITLE
Add support to s390x arch

### ISSUE THREAD

**Issue by dilipgb** [cert-manager/trust-manager#300]
trust manager tool is currently supported for amd, arm and power architectures. We need to enable the trust manager on s390x architecture as well.

**Comment by rishikakedia** [comment]
#315  here is PR for this issue. Please review.

**Comment by SgtCoDFish** [comment]
It's worth saying here that we won't be testing trust-manager on s390x any time soon. I don't see much harm in adding support for it (since it's easy in go!) but it'll be similar to cert-manager in that we won't actually test much on s390x!

**Comment by SgtCoDFish** [comment]
Quick question for you both; in #315  @rishikakedia says this:

> This is pre-req required for trust bundle integration for knative eventing.

Why does knative eventing require s390x in this case? Does knative require a set of architectures to be supported?

I've not really used knative at all, so I'm curious to learn more!

**Comment by dilipgb** [comment]
@SgtCoDFish we are working on porting knative to s390x. We are  knative on s390x and not the other way knative needs s390x. trust manager and cert manager is one of the dependency to enable for s390x.

**Comment by SgtCoDFish** [comment]
My pleasure, thank you for getting involved! I'll close this now since the PR merged; should be doing a new trust-manager release this week too!

**Comment by dilipgb** [comment]
@SgtCoDFish please excuse me for commenting on closed issue. I didn't find any channel related in cncf slack, hence using the same thread and not creating multiple issues.

We had one request regarding [trust-manager-package-debian](https://quay.io/repository/jetstack/cert-manager-package-debian) image referred. Can we get it published for s390x as well? We are facing issue with init containers. We tried building locally using command ``make trust-package-debian-save DEBIAN_TRUST_PACKAGE_VERSION="latest"`` and that works fine. I assume this is where the image is getting built, please correct me if I'm wrong.

**Comment by SgtCoDFish** [comment]
Ah it's absolutely OK to comment here! For future reference, we're on Kubernetes slack: https://cert-manager.io/docs/contributing/#slack

I totally didn't think about the Debian package! I'll see what I can do about that tomorrow, hopefully we should be able to get one published pretty quickly!
