### ISSUE TITLE
Avoid multiple decode/encode of certificates

### ISSUE THREAD

**Issue by erikgb** [cert-manager/trust-manager#305]
I have a feeling we are decoding/encoding certs in bundles multiple times already, and this adds another round of decode/encode. What about using a "Cert Pool" as an intermediate format between functions - instead of `[]string` or `[]byte`? We could fix this in a follow-up PR. Just wanted to note it here.

_Originally posted by @erikgb in https://github.com/cert-manager/trust-manager/pull/303#discussion_r1501880524_

**Comment by arsenalzp** [comment]
Hello,
Can I work on this?
If we have the final decision, I cat work on this issue to improve code usage and performance.
I would appreciate any suggestions how can we improve.
As far as I remember `CertPool` usage was suggested.

**Comment by erikgb** [comment]
Please do, @arsenalzp! 🎉 Anything that needs to be decided?

**Comment by arsenalzp** [comment]
> Please do, @arsenalzp! 🎉 Anything that needs to be decided?

As usually, during the work process we finding out the best decision :)

**Comment by erikgb** [comment]
@arsenalzp Are you working on this issue? If not, I am considering to take a stab. 🤠

**Comment by arsenalzp** [comment]
> @arsenalzp Are you working on this issue? If not, I am considering to take a stab. 🤠

Hello,
Sure, I don't forget about this issue, however I pushed all my strengths to pass one of AWS Architect exam.
Please, don't re-assign this issue to anyone else, I will manage with it soon :)

**Comment by arsenalzp** [comment]
I started working on this issue.

**Comment by arsenalzp** [comment]
Hello,
How do you think, should be maintain CertPool  structure between all functions: in source.go, pem.go, cert_pool.go? Or just between pem.go and cert_pool.go and keep as it is in source.go?

**Comment by erikgb** [comment]
> Hello,
> 
> How do you think, should be maintain CertPool  structure between all functions: in source.go, pem.go, cert_pool.go? Or just between pem.go and cert_pool.go and keep as it is in source.go?

I am a bit out of context, but if it makes sense to keep the cert pool from source to target, I will imagine that would make the code more compact and easier to read/understand?

**Comment by erikgb** [comment]
I believe this can be closed after https://github.com/cert-manager/trust-manager/pull/375 is merged.

/close

**Comment by arsenalzp** [comment]
It happened, finally!
Thank you colleagues, you didn't forget about my work :)
