### ISSUE TITLE
Running make test-smoke or make test-integration deletes ~/.kube/config

### ISSUE THREAD

**Issue by jabdoa2** [cert-manager/trust-manager#384]
When you run `make test-smoke` or `make test-integration` it will purge all existing kubernetes configs. This is rather annoying if you work with multiple clusters. You always have to remember to backup your `~/.kube/config` or you have to recreate it later on.

**Comment by inteon** [comment]
See https://github.com/cert-manager/makefile-modules/issues/150.
Since all makefile logic in the _shared folder originates from the https://github.com/cert-manager/makefile-modules, we have to update that repository instead of changing it here.

**Comment by inteon** [comment]
tracked in https://github.com/cert-manager/makefile-modules/issues/150
