### ISSUE TITLE
The chart application version is not up to date

### ISSUE THREAD

**Issue by evgeni-roif-gong** [cert-manager/trust-manager#489]
Looks like the chart version in the 0.13 shows the 0.9 version.
This is up to date: https://artifacthub.io/packages/helm/cert-manager/trust-manager

This is the 0.13 tag:
https://github.com/cert-manager/trust-manager/blob/v0.13.0/deploy/charts/trust-manager/Chart.yaml

**Comment by erikgb** [comment]
Thanks for reporting this @evgeni-roif-gong! It appear like something isn't right. I will take a closer look.

**Comment by erikgb** [comment]
@evgeni-roif-gong It seems like the version is overwritten when a release is cut, but I agree that this is confusing. WDYT of setting a dummy version in Git like `0.0.0`? This should be improved, so I would like to keep this issue open - even if it is not a bug.
