### ISSUE TITLE
Cache correctness investigations

### ISSUE THREAD

**Issue by SgtCoDFish** [cert-manager/trust-manager#91]
In #90 @inteon implemented some changes to help with cache correctness, since trust-manager has to work around some limitations currently present in controller-runtime (see https://github.com/kubernetes-sigs/controller-runtime/pull/1962 which should help).

We believe that PR was an improvement, but there might be other issues that need addressing which Tim is looking into. 

> It seems like my PR just makes Secrets the same as the other resources, but there is a fix necessary to make everything work as intended (minimal caching etc.).
> [and to avoid] duplicate caching (see this comment for more info: https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/builder/options.go#L103-L132)
> My current hypothesis is that we cache every resource 2 times (one time metadata only and one time fully), I still have to check by running an actual example.

This is a tracking issue for that work, which is likely a sensible prerequisite for a 0.4.0 release.

**Comment by inteon** [comment]
Here you can see that the "client" in bundle is also backed by a cache
![image](https://user-images.githubusercontent.com/42113979/211596060-c62e34c4-877e-4745-ae74-3d7a75032ce2.png)
So I think this comment is wrong:
![image](https://user-images.githubusercontent.com/42113979/211596118-4ce5982e-2205-467c-8386-b6ab416581de.png)
So, when you make a "Get" request with that client, a new informer is started that will cache all resources of that type.

NOTE: Still not 100% certain
