### ISSUE TITLE
Better `kubectl describe` for useDefaultCAs

### ISSUE THREAD

**Issue by SgtCoDFish** [cert-manager/trust-manager#96]
The new `useDefaultCAs` option doesn't render nicely in `kubectl describe`:

```yaml
Spec:
  Sources:
    Use Default C As:  true
```

This is because `kubectl describe` tries to be clever about separating words but fails to work in this case.

The relevant code from `kubectl describe` is [here](https://github.com/kubernetes/kubernetes/blob/62d7937b2e81752d922f6690dfff565c4a6ae8ce/staging/src/k8s.io/kubectl/pkg/describe/describe.go#L349-L375).

Options:

1. Keep name and change upstream handling of the name. Likely hard and slow to roll out.
2. Keep name and somehow change how it's rendered. I can't see any way to do this currently.
3. Change name
4. Live with it

**Comment by achuchev** [comment]
My two cents, don't change it or change it to `useDefaultCertificateAuthorities`.

**Comment by SgtCoDFish** [comment]
We discussed this in standup today and I think our conclusion will be "live with it" :grin:
